# Generated by Django 5.2.8 on 2025-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_player_number',
            field=models.IntegerField(default=50),
        ),
    ]
