# Generated by Django 6.0.1 on 2026-02-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='video_url',
        ),
    ]
