# Generated by Django 6.0.1 on 2026-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ads_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.IntegerField(blank=True, null=True)),
                ('whatsapp_number', models.IntegerField(blank=True, null=True)),
                ('discord_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.RenameField(
            model_name='tournamentjoinrequest',
            old_name='whatsapp_number',
            new_name='bkash_number',
        ),
        migrations.RemoveField(
            model_name='tournamentjoinrequest',
            name='social_profile_url',
        ),
        migrations.AddField(
            model_name='tournamentjoinrequest',
            name='transaction_id',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
